plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kotlin.multiplatform) apply false
    alias(libs.plugins.kotlin.serialization) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.ktlint) apply false
    alias(libs.plugins.detekt)
    alias(libs.plugins.roborazzi) apply false
    alias(libs.plugins.google.services) apply false
    alias(libs.plugins.kover)
}

subprojects {
    apply(plugin = "org.jlleitschuh.gradle.ktlint")

    configure<org.jlleitschuh.gradle.ktlint.KtlintExtension> {
        android.set(true)
        outputColorName.set("RED")
    }
}

// Kover aggregation. The root project collects coverage from every production
// module listed below; each module also applies the plugin (see their
// build.gradle.kts) so Kover can instrument their test source sets. This
// includes all current JVM / Android unit test source sets plus the
// `:core:tunnel:integrationTest` task, which exercises real relay code paths
// (e.g. `LazyMtlsKeyManager.chooseClientAlias`) that unit tests don't cover.
//
// No `koverVerify` rule — report-only for now per issue #248.
val coveredProjects = listOf(
    ":app",
    ":core:tunnel",
    ":core:mcp",
    ":core:bridge",
    ":api",
    ":notifications",
    ":work",
    ":integrations",
)

dependencies {
    coveredProjects.forEach { path ->
        kover(project(path))
    }
}

// Exclude Android `testReleaseUnitTest` tasks from Kover. CI only runs debug
// unit tests (release variant tests have never been configured to work, e.g.
// Roborazzi screenshot tests in :notifications), so Kover's default behaviour
// of triggering both debug + release unit test tasks would fail. The debug
// variant's instrumented test results are sufficient since production code is
// identical between variants for coverage purposes.
subprojects {
    plugins.withId("org.jetbrains.kotlinx.kover") {
        extensions.configure<kotlinx.kover.gradle.plugin.dsl.KoverProjectExtension>("kover") {
            currentProject {
                instrumentation {
                    disabledForTestTasks.add("testReleaseUnitTest")
                }
            }
        }
    }
}

kover {
    reports {
        filters {
            excludes {
                // Generated Android build metadata
                classes("*.BuildConfig")
                classes("*.BuildConfig\$*")
                // Compose singletons + lambda classes generated by the compose compiler
                classes("*ComposableSingletons*")
                classes("*_ComposableKt*")
                classes("*.*\$ComposeLambda*")
                // kotlinx.serialization generated serializers/companions
                classes("*\$\$serializer")
                classes("*\$\$serializer\$*")
                // Hilt / Koin generated glue (future-proof; Hilt isn't wired today)
                classes("*_HiltModules*")
                classes("Hilt_*")
                classes("*_Factory")
                classes("*_Factory\$*")
                classes("*_MembersInjector")
                classes("*_MembersInjector\$*")
                classes("*ComponentManager*")
                // Room generated DAOs / databases
                classes("*_Impl")
                classes("*_Impl\$*")
            }
        }
    }
}

detekt {
    buildUponDefaultConfig = true
    config.setFrom("$rootDir/config/detekt/detekt.yml")
    source.setFrom(
        subprojects.map { "${it.projectDir}/src" }
    )
}
