package com.rousecontext.app.ui.screens

import java.io.File
import java.util.Collections

/**
 * Metadata for a single audit-row variant captured during
 * [AuditRowVariantsScreenshotTest]. Each variant produces one light + one
 * dark PNG; [screenshotBase] names the pair (e.g. `01_third_row`).
 *
 * Image paths in the rendered HTML are RELATIVE to the HTML file's location
 * (`docs/internal/audit-row-variants/index.html`), so the Pages workflow
 * copies the screenshots into a sibling `screenshots/` directory.
 */
internal data class CapturedVariant(
    val screenshotBase: String,
    val label: String,
    val description: String
) {
    val lightPng: String get() = "screenshots/${screenshotBase}_light.png"
    val darkPng: String get() = "screenshots/${screenshotBase}_dark.png"
}

/**
 * Thread-safe collector for [CapturedVariant]s. Populated by the screenshot
 * test's light + dark captures; the first record for a given base name wins
 * so the duplicate dark call is a no-op.
 */
internal object CapturedVariants {
    private val byBase: MutableMap<String, CapturedVariant> =
        Collections.synchronizedMap(LinkedHashMap())

    fun record(base: String, label: String, description: String) {
        synchronized(byBase) {
            if (byBase.containsKey(base)) return
            byBase[base] = CapturedVariant(
                screenshotBase = base,
                label = label,
                description = description
            )
        }
    }

    fun snapshot(): List<CapturedVariant> = synchronized(byBase) {
        byBase.values.toList()
    }

    fun clear() = synchronized(byBase) { byBase.clear() }
}

/**
 * Writes the audit-row variants catalog HTML to [outputFile]. Called from
 * the screenshot test's `@ClassRule` once every variant has been captured,
 * so the HTML references only screenshots that actually landed on disk.
 */
internal object AuditRowCatalogHtmlWriter {
    fun write(outputFile: File, variants: List<CapturedVariant>) {
        outputFile.parentFile?.mkdirs()
        outputFile.writeText(render(variants))
    }

    fun render(variants: List<CapturedVariant>): String {
        val sorted = variants.sortedBy { it.screenshotBase }
        return buildString {
            append(HEADER)
            append("<div class=\"container\">\n")
            append(
                "<p class=\"generated-note\">Generated by " +
                    "<code>AuditRowVariantsScreenshotTest</code>. Seven candidate " +
                    "client-label placement options for <code>ToolCallRow</code> " +
                    "(see <a href=\"" +
                    "https://github.com/monkopedia/rouse-context/issues/343" +
                    "\">#343</a>). " +
                    "Each variant renders three sample client labels &mdash; short " +
                    "(<code>Claude</code>), long (<code>Claude Desktop</code>), and " +
                    "unknown (<code>Unknown (#1)</code>) &mdash; in both light and " +
                    "dark theme. Production <code>ToolCallRow</code> is not " +
                    "modified.</p>\n"
            )
            for (variant in sorted) {
                append(renderVariant(variant))
            }
            append("</div>\n")
            append(FOOTER)
        }
    }

    private fun renderVariant(v: CapturedVariant): String = buildString {
        append("  <article class=\"variant\">\n")
        append("    <h2>").append(escape(v.label)).append("</h2>\n")
        append("    <p class=\"description\">").append(escape(v.description)).append("</p>\n")
        append("    <div class=\"screenshot-pair\">\n")
        append("      <figure>\n")
        append("        <img src=\"").append(escape(v.lightPng)).append("\" alt=\"")
            .append(escape(v.label)).append(" light\">\n")
        append("        <figcaption>Light</figcaption>\n")
        append("      </figure>\n")
        append("      <figure>\n")
        append("        <img src=\"").append(escape(v.darkPng)).append("\" alt=\"")
            .append(escape(v.label)).append(" dark\">\n")
        append("        <figcaption>Dark</figcaption>\n")
        append("      </figure>\n")
        append("    </div>\n")
        append("  </article>\n")
    }

    private fun escape(s: String): String = buildString(s.length) {
        for (ch in s) {
            when (ch) {
                '&' -> append("&amp;")
                '<' -> append("&lt;")
                '>' -> append("&gt;")
                '"' -> append("&quot;")
                '\'' -> append("&#39;")
                else -> append(ch)
            }
        }
    }

    private val HEADER = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Rouse Context &mdash; Audit Row Variants</title>
<style>
  :root {
    --bg: #f0f0f0;
    --card-bg: #ffffff;
    --card-border: rgba(0,0,0,0.08);
    --text-primary: #1a1a1a;
    --text-secondary: #5f6368;
    --text-tertiary: #80868b;
    --accent: #1a73e8;
    --divider: rgba(0,0,0,0.08);
    --code-bg: rgba(0,0,0,0.05);
  }
  body.dark {
    --bg: #1a1a1a;
    --card-bg: #2d2d2d;
    --card-border: rgba(255,255,255,0.08);
    --text-primary: #e8eaed;
    --text-secondary: #9aa0a6;
    --text-tertiary: #80868b;
    --accent: #8ab4f8;
    --divider: rgba(255,255,255,0.08);
    --code-bg: rgba(255,255,255,0.08);
  }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: "Roboto", "Google Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    background: var(--bg);
    color: var(--text-primary);
    transition: background 0.2s, color 0.2s;
  }
  header {
    background: var(--card-bg);
    border-bottom: 1px solid var(--divider);
    padding: 24px 32px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    position: sticky;
    top: 0;
    z-index: 100;
  }
  header h1 { font-size: 22px; font-weight: 500; letter-spacing: -0.2px; }
  header h1 span { color: var(--text-secondary); font-weight: 400; }
  .theme-toggle {
    background: var(--code-bg);
    border: 1px solid var(--divider);
    color: var(--text-secondary);
    padding: 8px 16px;
    border-radius: 20px;
    cursor: pointer;
    font-size: 14px;
    font-family: inherit;
  }
  .theme-toggle:hover { background: var(--divider); }
  .container { max-width: 960px; margin: 0 auto; padding: 24px 16px 64px; }
  .generated-note {
    font-size: 13px;
    color: var(--text-secondary);
    background: var(--code-bg);
    border: 1px solid var(--divider);
    border-radius: 8px;
    padding: 10px 14px;
    margin-bottom: 24px;
    line-height: 1.5;
  }
  .generated-note code {
    font-family: "Roboto Mono", "SF Mono", Consolas, monospace;
    font-size: 12px;
  }
  .generated-note a { color: var(--accent); text-decoration: none; }
  .generated-note a:hover { text-decoration: underline; }
  .variant {
    background: var(--card-bg);
    border: 1px solid var(--card-border);
    border-radius: 12px;
    padding: 20px;
    margin-bottom: 20px;
  }
  .variant h2 {
    font-size: 17px;
    font-weight: 600;
    color: var(--text-primary);
    margin-bottom: 6px;
  }
  .description {
    font-size: 13px;
    color: var(--text-secondary);
    margin-bottom: 14px;
    line-height: 1.5;
  }
  .screenshot-pair {
    display: flex;
    gap: 20px;
    flex-wrap: wrap;
  }
  .screenshot-pair figure {
    display: flex;
    flex-direction: column;
    align-items: center;
  }
  .screenshot-pair img {
    border-radius: 10px;
    border: 1px solid var(--card-border);
    max-width: 360px;
    width: 100%;
    height: auto;
    display: block;
  }
  .screenshot-pair figcaption {
    font-size: 11px;
    color: var(--text-tertiary);
    margin-top: 6px;
    text-transform: uppercase;
    letter-spacing: 0.6px;
  }
</style>
</head>
<body>
<header>
  <h1>Rouse Context <span>Audit Row Variants (#343)</span></h1>
  <button class="theme-toggle" onclick="toggleTheme()">Dark Mode</button>
</header>
    """.trimIndent() + "\n"

    private val FOOTER = """
<script>
function toggleTheme() {
  document.body.classList.toggle("dark");
  const btn = document.querySelector(".theme-toggle");
  btn.textContent = document.body.classList.contains("dark") ? "Light Mode" : "Dark Mode";
}
</script>
</body>
</html>
    """.trimIndent() + "\n"
}
