package com.rousecontext.notifications.preview

import android.app.Notification
import java.io.File
import java.util.Collections

/**
 * Captured metadata for a single notification variant rendered during
 * [NotificationScreenshotTest]. Populated from the real [Notification]
 * posted by a production notifier (title/body/sub-text read directly from
 * [Notification.extras] rather than hand-typed in the catalog HTML).
 */
internal data class CapturedNotification(
    val notifier: String,
    val variantLabel: String,
    val title: String?,
    val body: String?,
    val subText: String?,
    val channelId: String?,
    val screenshotBase: String
) {
    val lightPng: String get() = "../../notifications/screenshots/${screenshotBase}_light.png"
    val darkPng: String get() = "../../notifications/screenshots/${screenshotBase}_dark.png"
}

/**
 * Thread-safe collector for [CapturedNotification]s. The screenshot test
 * fires `@Test`s for each (case, theme) pair; this records one metadata
 * entry per screenshot base name (first write wins) so duplicate calls
 * from the light + dark captures are a no-op.
 */
internal object CapturedNotifications {
    private val byBase: MutableMap<String, CapturedNotification> =
        Collections.synchronizedMap(LinkedHashMap())

    fun record(
        screenshotBase: String,
        notifier: String,
        variantLabel: String,
        notification: Notification
    ) {
        synchronized(byBase) {
            if (byBase.containsKey(screenshotBase)) return
            val extras = notification.extras
            byBase[screenshotBase] = CapturedNotification(
                notifier = notifier,
                variantLabel = variantLabel,
                title = extras.getCharSequence(Notification.EXTRA_TITLE)?.toString(),
                body = extras.getCharSequence(Notification.EXTRA_TEXT)?.toString(),
                subText = extras.getCharSequence(Notification.EXTRA_SUB_TEXT)?.toString(),
                channelId = notification.channelId,
                screenshotBase = screenshotBase
            )
        }
    }

    fun snapshot(): List<CapturedNotification> = synchronized(byBase) {
        byBase.values.toList()
    }

    fun clear() = synchronized(byBase) { byBase.clear() }
}

/**
 * Writes the QA notification catalog HTML to [outputFile], deriving
 * every title, body, sub-text, and image reference from the supplied
 * [CapturedNotification]s. No notification copy is hand-typed; running
 * the screenshot test is the ONLY way this file changes.
 */
internal object NotificationCatalogHtmlWriter {
    fun write(outputFile: File, cases: List<CapturedNotification>) {
        outputFile.parentFile?.mkdirs()
        outputFile.writeText(render(cases))
    }

    fun render(cases: List<CapturedNotification>): String {
        // Sort by screenshot base name (e.g. `01_foreground_connecting`) so the
        // generated HTML is deterministic regardless of JUnit test execution
        // order. The numeric prefix groups variants of the same notifier
        // together in their natural display sequence.
        val sorted = cases.sortedBy { it.screenshotBase }
        // Preserve first-seen notifier order from the sorted list.
        val grouped: Map<String, List<CapturedNotification>> =
            sorted.groupByTo(LinkedHashMap()) { it.notifier }
        return buildString {
            append(HEADER)
            append("<div class=\"container\">\n")
            append(
                "<p class=\"generated-note\">Generated by " +
                    "<code>NotificationScreenshotTest</code>. " +
                    "All titles, body text, sub-text, and channel IDs below are read " +
                    "directly from the <code>Notification</code> objects posted by " +
                    "production notifiers during the test run.</p>\n"
            )
            for ((notifier, variants) in grouped) {
                append("<section class=\"notifier-section\">\n")
                append("  <h2>").append(escape(notifier)).append("</h2>\n")
                for (variant in variants) {
                    append(renderVariant(variant))
                }
                append("</section>\n")
            }
            append("</div>\n")
            append(FOOTER)
        }
    }

    private fun renderVariant(v: CapturedNotification): String = buildString {
        append("  <article class=\"variant\">\n")
        append("    <h3>").append(escape(v.variantLabel)).append("</h3>\n")
        append("    <dl class=\"fields\">\n")
        field("Title", v.title)
        field("Body", v.body)
        if (v.subText != null) field("Sub-text", v.subText)
        field("Channel", v.channelId)
        append("    </dl>\n")
        append("    <div class=\"screenshot-pair\">\n")
        append("      <figure>\n")
        append("        <img src=\"").append(escape(v.lightPng)).append("\" alt=\"")
            .append(escape(v.variantLabel)).append(" light\">\n")
        append("        <figcaption>Light</figcaption>\n")
        append("      </figure>\n")
        append("      <figure>\n")
        append("        <img src=\"").append(escape(v.darkPng)).append("\" alt=\"")
            .append(escape(v.variantLabel)).append(" dark\">\n")
        append("        <figcaption>Dark</figcaption>\n")
        append("      </figure>\n")
        append("    </div>\n")
        append("  </article>\n")
    }

    private fun StringBuilder.field(label: String, value: String?) {
        append("      <dt>").append(escape(label)).append("</dt>\n")
        append("      <dd><code>")
        append(if (value.isNullOrEmpty()) "&mdash;" else escape(value))
        append("</code></dd>\n")
    }

    private fun escape(s: String): String = buildString(s.length) {
        for (ch in s) {
            when (ch) {
                '&' -> append("&amp;")
                '<' -> append("&lt;")
                '>' -> append("&gt;")
                '"' -> append("&quot;")
                '\'' -> append("&#39;")
                else -> append(ch)
            }
        }
    }

    private val HEADER = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Rouse Context &mdash; Notification Catalog</title>
<style>
  :root {
    --bg: #f0f0f0;
    --card-bg: #ffffff;
    --card-border: rgba(0,0,0,0.08);
    --text-primary: #1a1a1a;
    --text-secondary: #5f6368;
    --text-tertiary: #80868b;
    --accent: #1a73e8;
    --divider: rgba(0,0,0,0.08);
    --code-bg: rgba(0,0,0,0.05);
  }
  body.dark {
    --bg: #1a1a1a;
    --card-bg: #2d2d2d;
    --card-border: rgba(255,255,255,0.08);
    --text-primary: #e8eaed;
    --text-secondary: #9aa0a6;
    --text-tertiary: #80868b;
    --accent: #8ab4f8;
    --divider: rgba(255,255,255,0.08);
    --code-bg: rgba(255,255,255,0.08);
  }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: "Roboto", "Google Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    background: var(--bg);
    color: var(--text-primary);
    transition: background 0.2s, color 0.2s;
  }
  header {
    background: var(--card-bg);
    border-bottom: 1px solid var(--divider);
    padding: 24px 32px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    position: sticky;
    top: 0;
    z-index: 100;
  }
  header h1 { font-size: 22px; font-weight: 500; letter-spacing: -0.2px; }
  header h1 span { color: var(--text-secondary); font-weight: 400; }
  .theme-toggle {
    background: var(--code-bg);
    border: 1px solid var(--divider);
    color: var(--text-secondary);
    padding: 8px 16px;
    border-radius: 20px;
    cursor: pointer;
    font-size: 14px;
    font-family: inherit;
  }
  .theme-toggle:hover { background: var(--divider); }
  .container { max-width: 920px; margin: 0 auto; padding: 24px 16px 64px; }
  .generated-note {
    font-size: 13px;
    color: var(--text-secondary);
    background: var(--code-bg);
    border: 1px solid var(--divider);
    border-radius: 8px;
    padding: 10px 14px;
    margin-bottom: 24px;
    line-height: 1.5;
  }
  .generated-note code {
    font-family: "Roboto Mono", "SF Mono", Consolas, monospace;
    font-size: 12px;
  }
  .notifier-section { margin-bottom: 40px; }
  .notifier-section h2 {
    font-size: 16px;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.8px;
    color: var(--text-tertiary);
    margin-bottom: 12px;
    padding: 0 4px;
  }
  .variant {
    background: var(--card-bg);
    border: 1px solid var(--card-border);
    border-radius: 12px;
    padding: 16px;
    margin-bottom: 12px;
  }
  .variant h3 {
    font-size: 15px;
    font-weight: 600;
    color: var(--text-primary);
    margin-bottom: 10px;
  }
  .fields {
    display: grid;
    grid-template-columns: max-content 1fr;
    column-gap: 10px;
    row-gap: 4px;
    margin-bottom: 12px;
    font-size: 13px;
  }
  .fields dt {
    color: var(--text-tertiary);
    font-weight: 500;
  }
  .fields dd code {
    font-family: "Roboto Mono", "SF Mono", Consolas, monospace;
    font-size: 12px;
    background: var(--code-bg);
    padding: 1px 6px;
    border-radius: 4px;
    color: var(--text-primary);
    word-break: break-word;
  }
  .screenshot-pair {
    display: flex;
    gap: 16px;
    flex-wrap: wrap;
  }
  .screenshot-pair figure {
    display: flex;
    flex-direction: column;
    align-items: center;
  }
  .screenshot-pair img {
    border-radius: 10px;
    border: 1px solid var(--card-border);
    max-width: 240px;
    height: auto;
    display: block;
  }
  .screenshot-pair figcaption {
    font-size: 11px;
    color: var(--text-tertiary);
    margin-top: 4px;
    text-transform: uppercase;
    letter-spacing: 0.6px;
  }
</style>
</head>
<body>
<header>
  <h1>Rouse Context <span>Notification Catalog</span></h1>
  <button class="theme-toggle" onclick="toggleTheme()">Dark Mode</button>
</header>
    """.trimIndent() + "\n"

    private val FOOTER = """
<script>
function toggleTheme() {
  document.body.classList.toggle("dark");
  const btn = document.querySelector(".theme-toggle");
  btn.textContent = document.body.classList.contains("dark") ? "Light Mode" : "Dark Mode";
}
</script>
</body>
</html>
    """.trimIndent() + "\n"
}
